/*
 * hydra_stat.h
 *
 *  Created on: Oct 19, 2015
 *      Author: root
 */

#ifndef HYDRA_STAT_H_
#define HYDRA_STAT_H_


#include <string.h>
#include <stdint.h>


typedef struct{
    uint32_t index;
    uint32_t num;
} hydra_stat_op_in_t;

typedef struct
{
    uint32_t module;
    uint32_t lvl;
} npcp_dp_log_lvl_set_t;

#define HYDRA_STAT_NAME_SIZE      128
typedef enum
{
    stat_pkt,
    stat_npcp_rx_pkt,
    stat_npcp_core0_pkt,
    stat_npcp_core1_pkt,
    stat_npcp_core2_pkt,
    stat_npcp_core3_pkt,
    stat_npcp_core4_pkt,
    stat_npcp_core5_pkt,
    stat_npcp_core6_pkt,
    stat_npcp_core7_pkt,
    stat_npcp_core8_pkt,
    stat_npcp_core9_pkt,
    stat_npcp_core10_pkt,
    stat_npcp_core11_pkt,
    stat_npcp_core12_pkt,
    stat_npcp_core13_pkt,
    stat_npcp_core14_pkt,
    stat_npcp_core15_pkt,
    stat_npcp_core16_pkt,
    stat_npcp_core17_pkt,
    stat_npcp_core18_pkt,
    stat_npcp_core19_pkt,
    stat_npcp_core20_pkt,
    stat_npcp_core21_pkt,
    stat_npcp_core22_pkt,
    stat_npcp_core23_pkt,
    stat_npcp_core24_pkt,
    stat_npcp_core25_pkt,
    stat_npcp_core26_pkt,
    stat_npcp_core27_pkt,
    stat_npcp_core28_pkt,
    stat_npcp_core29_pkt,
    stat_npcp_core30_pkt,
    stat_npcp_core31_pkt,
    stat_npcp_core32_pkt,
    stat_npcp_core33_pkt,
    stat_npcp_core34_pkt,
    stat_npcp_core35_pkt,
    stat_npcp_core36_pkt,
    stat_npcp_core37_pkt,
    stat_npcp_core38_pkt,
    stat_npcp_core39_pkt,
    stat_npcp_core40_pkt,
    stat_npcp_core41_pkt,
    stat_npcp_core42_pkt,
    stat_npcp_core43_pkt,
    stat_npcp_core44_pkt,
    stat_npcp_core45_pkt,
    stat_npcp_core46_pkt,
    stat_npcp_core47_pkt,
    stat_npcp_rx_unknown_pkt,
    stat_npcp_rx_err_pkt,
    stat_npcp_unregistered_pkt,
    stat_npcp_send_buff_null,
    stat_npcp_tx_pkt,
    stat_npcp_tx_fail_pkt,
    stat_npcp_free,
    stat_business_pkt,
    stat_business_core0_pkt,
    stat_business_core1_pkt,
    stat_business_core2_pkt,
    stat_business_core3_pkt,
    stat_business_core4_pkt,
    stat_business_core5_pkt,
    stat_business_core6_pkt,
    stat_business_core7_pkt,
    stat_business_core8_pkt,
    stat_business_core9_pkt,
    stat_business_core10_pkt,
    stat_business_core11_pkt,
    stat_business_core12_pkt,
    stat_business_core13_pkt,
    stat_business_core14_pkt,
    stat_business_core15_pkt,
    stat_business_core16_pkt,
    stat_business_core17_pkt,
    stat_business_core18_pkt,
    stat_business_core19_pkt,
    stat_business_core20_pkt,
    stat_business_core21_pkt,
    stat_business_core22_pkt,
    stat_business_core23_pkt,
    stat_business_core24_pkt,
    stat_business_core25_pkt,
    stat_business_core26_pkt,
    stat_business_core27_pkt,
    stat_business_core28_pkt,
    stat_business_core29_pkt,
    stat_business_core30_pkt,
    stat_business_core31_pkt,
    stat_business_core32_pkt,
    stat_business_core33_pkt,
    stat_business_core34_pkt,
    stat_business_core35_pkt,
    stat_business_core36_pkt,
    stat_business_core37_pkt,
    stat_business_core38_pkt,
    stat_business_core39_pkt,
    stat_business_core40_pkt,
    stat_business_core41_pkt,
    stat_business_core42_pkt,
    stat_business_core43_pkt,
    stat_business_core44_pkt,
    stat_business_core45_pkt,
    stat_business_core46_pkt,
    stat_business_core47_pkt,
    stat_business_soft_err_pkt,
    stat_business_parse_pkt,
    stat_business_parse_err_pkt,
    stat_ipv4_pkt,
    stat_ipv6_pkt,
    stat_ipv4_pkt_hd,
    stat_ipv6_pkt_hd,
    stat_outertcp_pkt,
    stat_outerudp_pkt,
    stat_outerother_pkt,
    stat_innertcp_pkt,
    stat_innerudp_pkt,
    stat_innerother_pkt,

    stat_pkts_lte,
    stat_pkts_iups,
    stat_pkts_permit_not_lte,
    stat_pkts_gtpu,
    stat_pkts_gtpu_header_error,
    stat_pkts_gtpu_inner_version_error,
    stat_pkts_gtpu_inner_ip_protocol_error,
    stat_pkts_gtpu_mt_error,
    stat_pkts_gtpu_match_port,
    stat_pkts_gtpu_custom_port,
    stat_pkts_gtpv2c,
    stat_pkts_gtpv2c_match_port,
    stat_pkts_gtpv2c_custom_port,
    stat_pkts_gtpv2c_imsi_invalid,
    stat_pkts_gtpv2c_imei_invalid,
    stat_pkts_gtpv2c_msisdn_invalid,
    stat_pkts_gtpv1c,
    stat_pkts_gtpv1c_match_port,
    stat_pkts_gtpv1c_custom_port,
    stat_pkts_gtpv1c_with_seq,
    stat_pkts_gtpv1c_without_seq,
    stat_pkts_gtpv1c_with_npdu_ex_flag,
    stat_pkts_gtpv1c_imsi_invalid,
    stat_pkts_gtpv1c_msisdn_invalid,
    stat_pkts_gtpv1c_imei_invalid,
    stat_pkts_gtpv1c_cur_invalid,
    stat_pkts_gtpc_hd,
    stat_pkts_not_gtp,
    stat_business_iifgrp_fail_pkt,
    stat_business_iifgrp_invalid_pkt,
    stat_business_iifgrp_out_range,
    stat_business_grpwork_null,
    stat_pkts_lte_relate_failed,
    stat_pkts_gtpu_related,
    stat_pkts_gtpu_related_supply,
    stat_pkts_gtpc_create_session_req,
    stat_pkts_gtpc_create_session_req_related,
    stat_pkts_gtpc_create_session_rsp,
    stat_pkts_gtpc_create_session_rsp_related,
    stat_pkts_gtpc_modify_bearer_req,
    stat_pkts_gtpc_modify_bearer_req_related,
    stat_pkts_gtpc_modify_bearer_res,
    stat_pkts_gtpc_modify_bearer_res_related,

    stat_pkts_gtpc_delete_session_req,
    stat_pkts_gtpc_delete_session_req_related,
    stat_pkts_gtpc_delete_session_rsp,
    stat_pkts_gtpc_delete_session_rsp_related,

    stat_pkts_gtpc_delete_bearer_req,
    stat_pkts_gtpc_delete_bearer_req_related,
    stat_pkts_gtpc_delete_bearer_rsp,
    stat_pkts_gtpc_delete_bearer_rsp_related,

    stat_pkts_gtpc_create_bearer_req,
    stat_pkts_gtpc_create_bearer_req_related,
    stat_pkts_gtpc_create_bearer_rsp,
    stat_pkts_gtpc_create_bearer_rsp_related,

    /*for gtpv1c*/
    stat_pkts_gtpv1c_create_pdp_context_request,
    stat_pkts_gtpv1c_create_pdp_context_response,
    stat_pkts_gtpv1c_update_pdp_context_request,
    stat_pkts_gtpv1c_delete_pdp_context_response,
    stat_pkts_gtpv1c_para_imsi_invalid,
    stat_pkts_gtpv1c_ip_teid_invalid,
    stat_pkts_gtpv1c_para_pdn_invalid,

    stat_pkts_imsi_table_failed,
    stat_pkts_s11_mme_table_failed,
    stat_pkts_s11_sgw_table_failed,

    stat_pkts_s1u_table_failed_2,               /* 第2，3，4均有，区分开*/
    stat_pkts_s1u_table_failed_3,
    stat_pkts_s1u_table_failed_4,
    stat_pkts_s1u_table_failed_gtpu,

    stat_pkts_imsi_entry_unexpect_null,
    stat_pkts_s11_mme_entry_unexpect_null,
    stat_pkts_s11_sgw_entry_unexpect_null,
    stat_pkts_s1u_entry_unexpect_null,

    stat_pkts_imsi_table_incompelte,
    stat_pkts_s11_mme_table_incompelte,
    stat_pkts_s11_sgw_table_incompelte,
    stat_pkts_s1u_table_incompelte,
    stat_pkts_s1u_table_ueip_nocompare,
    stat_pkts_s1u_pnd_over,
    stat_pkts_imsi_unexpect_free,
    stat_pkts_response_reject,
    stat_pkts_info_incompelte_1,                /* 第1，2，3，4均有，区分开*/
    stat_pkts_info_incompelte_2,
    stat_pkts_info_incompelte_3,
    stat_pkts_info_incompelte_4,
    stat_pkts_info_incompelte_erab_rst,
    stat_pkts_info_incompelte_erab_rsp,
    stat_pkts_imsi_info_not_bcd,
    stat_pkts_imsi_new_cell_fail,
    stat_pkts_s11_mme_new_cell_fail,
    stat_pkts_s11_sgw_new_cell_fail,
    stat_pkts_s1u_new_cell_fail,

/* s1ap related counters */
    stat_pkts_s1ap_initialUEMessage,
    stat_pkts_s1ap_ciphered_initialUEMessage,
    stat_pkts_s1ap_imsi_initialUEMessage,
    stat_pkts_s1ap_old_guti_initialUEMessage,
    stat_pkts_s1ap_invalid_initialUEMessage,
    stat_pkts_s1ap_not_found_imsi_from_STMSI,
    stat_pkts_s1ap_alg_type_set,
    stat_pkts_s1ap_get_kasme_failed,
    stat_pkts_s1ap_update_imsi_kasme_failed,
    stat_pkts_s1ap_update_imsi_kasme_success,
    stat_pkts_s1ap_search_imsi_kasme_failed,
    stat_pkts_s1ap_guti_invalid,
    stat_pkts_s1ap_uplinkNASTransport_update_imsi,

    stat_pkts_InitialContextSetup,
    stat_pkts_InitialContextSetup_no_ciphered,
    stat_pkts_InitialContextSetup_witchout_nas,

    stat_pkts_AttachRequest,
    stat_pkts_NotAttachRequest,
    stat_pkts_AttachAccept,
    stat_pkts_NotAttachAccept,


    stat_decrypt_failed,
    stat_parse_guti_failed,
    stat_pkts_create_stmsi_table,
    stat_pkts_stmsi_table_failed,

    stat_lte_uecontextsetup_creat_cn_info_fail,

/* IuPS related counters */
    stat_pkts_IuPS_not_found_imsi_from_PTMSI,
    stat_pkts_IuPS_attach_request_not_found_valid_imsi,
    stat_pkts_IuPS_search_imsi_table_failed,
    stat_pkts_create_an_info_table_failed,
    stat_pkts_search_an_info_table_failed,
    stat_pkts_update_an_info_table_failed,
    stat_pkts_create_cn_info_table_failed,
    stat_pkts_search_cn_info_table_failed,
    stat_pkts_update_cn_info_table_failed,
    stat_pkts_update_imsi_table_failed,
    stat_pkts_create_p_tmsi_table_failed,
    stat_pkts_search_p_tmsi_table_failed,
    stat_pkts_update_p_tmsi_table_failed,

    stat_pkts_create_gtp_u_table_failed,
    stat_pkts_search_gtp_u_table_failed,
    stat_pkts_update_gtp_u_table_failed,
    stat_pkts_gtp_u_table_info_without_imsi,

    stat_pkts_Iups_gmm_attach_request,
    stat_pkts_Iups_gmm_attach_accept,
    stat_pkts_Iups_gmm_rau_accept,
    stat_pkts_Iups_gmm_identify_response,
    stat_pkts_Iups_gmm_reallocCmd,
    stat_pkts_Iups_gmm_deattach_accept,

    stat_pkts_Iups_ranap_initialUeMsg,
    stat_pkts_Iups_ranap_initialUeMsg_attachreq,
    stat_pkts_Iups_ranap_commonID,
    stat_pkts_Iups_ranap_commonID_cc,
    stat_pkts_Iups_ranap_commonID_dt1,
    stat_pkts_Iups_ranap_directTransfer,
    stat_pkts_Iups_ranap_directTrans_cc,
    stat_pkts_Iups_ranap_directTrans_attachreq,
    stat_pkts_Iups_ranap_directTrans_attachacc,
    stat_pkts_Iups_ranap_directTrans_rauacc,
    stat_pkts_Iups_ranap_directTrans_identityres,
    stat_pkts_Iups_ranap_directTrans_realloccmd,
    stat_pkts_Iups_ranap_directTrans_deattachacc,
    stat_pkts_Iups_ranap_rabAssigReq,
    stat_pkts_Iups_ranap_rabAssigRes,
    stat_pkts_Iups_ranap_IuRelease,
    stat_pkts_Iups_sccp_cr_without_ranap,
    stat_pkts_Iups_sccp_cc_without_ranap,

    stat_pkts_Iups_gmm_attachReq_IupsInfo_isNull,
    stat_pkts_Iups_gmm_attachReq_no_sccpDlr,
    stat_pkts_Iups_gmm_attachReq_find_cnTable,
    stat_pkts_Iups_gmm_attachReq_find_anTable,
    stat_pkts_Iups_gmm_attachReq_create_imsiTable,
    stat_pkts_Iups_gmm_attachAcc_IupsInfo_isNull,
    stat_pkts_Iups_gmm_attachAcc_no_sccpDlr,
    stat_pkts_Iups_gmm_attachAcc_pTmsi_valid,
    stat_pkts_Iups_gmm_attachAcc_find_anTable,
    stat_pkts_Iups_gmm_attachAcc_anTable_imsi_invalid,
    stat_pkts_Iups_gmm_attachAcc_create_pTmsiT,
    stat_pkts_Iups_gmm_attachAcc_up_imsiT_pTmsi,
    stat_pkts_Iups_gmm_rauAcc_IupsInfo_isNull,
    stat_pkts_Iups_gmm_rauAcc_no_sccpDlr_or_rai,
    stat_pkts_Iups_gmm_rauAcc_up_anTable_rai,
    stat_pkts_Iups_gmm_rauAcc_find_imsiT,
    stat_pkts_Iups_gmm_rauAcc_create_pTmsiT,
    stat_pkts_Iups_gmm_rauAcc_up_imsiT,
    stat_pkts_Iups_gmm_idenRes_IupsInfo_isNull,
    stat_pkts_Iups_gmm_idenRes_no_sccpDlr,
    stat_pkts_Iups_gmm_idenRes_no_imsiAndimei,
    stat_pkts_Iups_gmm_idenRes_imsi_valid,
    stat_pkts_Iups_gmm_idenRes_find_cnT,
    stat_pkts_Iups_gmm_idenRes_up_cnT_imsi,
    stat_pkts_Iups_gmm_idenRes_find_anT,
    stat_pkts_Iups_gmm_idenRes_up_anT_imsi,
    stat_pkts_Iups_gmm_idenRes_create_imsiT,
    stat_pkts_Iups_gmm_idenRes_imei_vaild,
    stat_pkts_Iups_gmm_idenRes_imei_find_cnT,
    stat_pkts_Iups_gmm_idenRes_imei_cnT_no_imsi,
    stat_pkts_Iups_gmm_idenRes_imei_create_imsiT,
    stat_pkts_Iups_gmm_reallocCmd_IupsInfo_isNull,
    stat_pkts_Iups_gmm_reallocCmd_no_sccpDlrOrPtmsi,
    stat_pkts_Iups_gmm_reallocCmd_find_anT,
    stat_pkts_Iups_gmm_reallocCmd_create_pTmsiT,
    stat_pkts_Iups_gmm_reallocCmd_up_imsiT_pTmsi,
    stat_pkts_Iups_gmm_deattachacc_IupsInfo_isNull,
    stat_pkts_Iups_gmm_deattachacc_no_sccpDlr,
    stat_pkts_Iups_gmm_deattachacc_upLink,
    stat_pkts_Iups_gmm_deattachacc_upLink_find_cnT,
    stat_pkts_Iups_gmm_deattachacc_upLink_cnTNoImsi,
    stat_pkts_Iups_gmm_deattachacc_downLink,
    stat_pkts_Iups_gmm_deattachacc_down_find_anT,
    stat_pkts_Iups_gmm_deattachacc_down_anTNoImsi,
    stat_pkts_Iups_ranap_iniUeMsg_IupsInfo_isNull,
    stat_pkts_Iups_ranap_iniUeMsg_sccp_no_CrOrSlr,
    stat_pkts_Iups_ranap_iniUeMsg_gmm_notCare,
    stat_pkts_Iups_ranap_iniUeMsg_gmm_pTmsi_valid,
    stat_pkts_Iups_ranap_iniUeMsg_find_pTmsiT,
    stat_pkts_Iups_ranap_iniUeMsg_create_anT,
    stat_pkts_Iups_ranap_iniUeMsg_attachreq_createImsiT,
    stat_pkts_Iups_ranap_commonID_IupsInfo_isNull,
    stat_pkts_Iups_ranap_commonID_imsi_invalid,
    stat_pkts_Iups_ranap_commonID_cc_createAnT,
    stat_pkts_Iups_ranap_commonID_cc_findAnT,
    stat_pkts_Iups_ranap_commonID_cc_create_cnT,
    stat_pkts_Iups_ranap_commonID_cc_up_anT,
    stat_pkts_Iups_ranap_commonID_cc_create_imsiT,
    stat_pkts_Iups_ranap_commonID_cc_up_imsiT,
    stat_pkts_Iups_ranap_commonID_dt1_noDlr,
    stat_pkts_Iups_ranap_commonID_dt1_find_anT,
    stat_pkts_Iups_ranap_commonID_dt1_find_cnT,
    stat_pkts_Iups_ranap_dirTrans_IupsInfo_isNull,
    stat_pkts_Iups_ranap_dirTrans_cc_create_anT,
    stat_pkts_Iups_ranap_dirTrans_cc_find_anT,
    stat_pkts_Iups_ranap_dirTrans_cc_create_cnT,
    stat_pkts_Iups_ranap_dirTrans_cc_up_imsiT,
    stat_pkts_Iups_ranap_dirTrans_cc_up_anT,
    stat_pkts_Iups_ranap_rabAsreq_IupsInfo_isNull,
    stat_pkts_Iups_ranap_rabAsreq_no_dlr,
    stat_pkts_Iups_ranap_rabAsreq_trasInfo_invalid,
    stat_pkts_Iups_ranap_rabAsreq_find_gtpuT,
    stat_pkts_Iups_ranap_rabAsreq_find_anT,
    stat_pkts_Iups_ranap_rabAsreq_up_anT,
    stat_pkts_Iups_ranap_rabAsreq_up_gtpuT_rai_fail,
    stat_pkts_Iups_ranap_rabAsreq_gtpuT_rai_valid,
    stat_pkts_Iups_ranap_rabAsreq_find_imsiT,
    stat_pkts_Iups_ranap_rabAsreq_up_imsiT,
    stat_pkts_Iups_ranap_rabAsres_IupsInfo_isNull,
    stat_pkts_Iups_ranap_rabAsres_no_dlr,
    stat_pkts_Iups_ranap_rabAsres_trasInfo_invalid,
    stat_pkts_Iups_ranap_rabAsres_find_cnT,
    stat_pkts_Iups_ranap_rabAsres_cnT_no_imsi,
    stat_pkts_Iups_ranap_rabAsres_find_imsiT,
    stat_pkts_Iups_ranap_rabAsres_create_gtpuT,
    stat_pkts_Iups_ranap_IuRelease_IupsInfo_isNull,
    stat_pkts_Iups_ranap_IuRelease_noDlrOrDirection,
    stat_pkts_Iups_ranap_IuRelease_find_anT,
    stat_pkts_Iups_sccp_cr_no_IupsInfo,
    stat_pkts_Iups_sccp_cr_no_slr,
    stat_pkts_Iups_sccp_cr_create_anT,
    stat_pkts_Iups_sccp_cc_no_IupsInfo,
    stat_pkts_Iups_sccp_cc_no_slrOrdlr,
    stat_pkts_Iups_sccp_cc_no_find_anT,
    stat_pkts_Iups_sccp_cc_create_anT,
    stat_pkts_Iups_sccp_cc_create_cnT,
    /*end Iups relate*/

/* add by zhengwan,Gn related counters,begin */
    stat_pkts_Gn_createreq_search_imsiTable_failed,
    stat_pkts_Gn_createreq_create_imsiTable_failed,
    stat_pkts_Gn_createreq_create_imsiTable,
    stat_pkts_Gn_createreq_update_imsiTable1_failed,
    stat_pkts_Gn_createreq_update_imsiTable1,
    stat_pkts_Gn_createreq_create_sgsnTable_failed,
    stat_pkts_Gn_createreq_create_sgsnTable,
    stat_pkts_Gn_createreq_update_imsiTable2_failed,
    stat_pkts_Gn_createreq_update_imsiTable2,

    stat_pkts_Gn_createrep_search_sgsnTable_failed,
    stat_pkts_Gn_createrep_search_imisTable_failed,
    stat_pkts_Gn_createrep_create_ggsnTable_failed,
    stat_pkts_Gn_createrep_create_ggsnTable,
    stat_pkts_Gn_createrep_create_gtpu_ulTable_failed,
    stat_pkts_Gn_createrep_create_gtpu_ulTable,
    stat_pkts_Gn_createrep_update_imsiTable_failed,
    stat_pkts_Gn_createrep_update_imsiTable,

    stat_pkts_Gn_updatereq_search_ggsnTable_failed,
    stat_pkts_Gn_updatereq_search_imsiTable_failed,
    stat_pkts_Gn_updatereq_search_gtpu_dlTable_failed,
    stat_pkts_Gn_updatereq_create_gtpu_dlTable_failed,
    stat_pkts_Gn_updatereq_create_gtpu_dlTable,
    stat_pkts_Gn_updatereq_update_imsiTable1_failed,
    stat_pkts_Gn_updatereq_update_imsiTable1,
    stat_pkts_Gn_updatereq_search_gtpu_ulTable1_failed,
    stat_pkts_Gn_updatereq_search_gtpu_ulTable2_failed,
    stat_pkts_Gn_updatereq_update_gtpu_ulTable1_failed,
    stat_pkts_Gn_updatereq_update_gtpu_ulTable1,
    stat_pkts_Gn_updatereq_update_gtpu_dlTable_failed,
    stat_pkts_Gn_updatereq_update_gtpu_dlTable,
    stat_pkts_Gn_updatereq_update_imsiTable2_failed,
    stat_pkts_Gn_updatereq_update_imsiTable2,
    stat_pkts_Gn_updatereq_update_gtpu_ulTable2_failed,
    stat_pkts_Gn_updatereq_update_gtpu_ulTable2,

    stat_pkts_Gn_deleterep_search_sgsnTable_failed,
    stat_pkts_Gn_deleterep_search_imsiTable_failed,
/* add by zhengwan, end*/

/*debug -s-*/
    stat_search_imsi_failed_1,
    stat_search_imsi_failed_2,
    stat_search_kasme_failed_1,
    stat_imsi_is_0,
    stat_RablistLengthOver255,
    stat_NaspduLengthOver255,

    stat_nas_attach_request_oldGuti,
    stat_nas_attach_request_imsi,
    stat_nas_tau_request_oldGuti,
    stat_nas_oldGuti_len_error,
    stat_nas_tau_request_imsi,
    stat_nas_identity_response_imsi,
    stat_nas_authentication_request,
    stat_nas_security_command,
    stat_nas_attach_accept,
    stat_ue_context_release_complete,

    stat_search_eNB_mme_handle_table_failed,

    stat_relate_identity_response_imsi,
    stat_relate_security_command,
    stat_relate_auth_request,
    stat_relate_UeContxtRelease,

    stat_hanover_notify_search_s1_mme_fail,

    stat_relate_detach_req,
    stat_relate_uplink_detach_accept,

/*debug -e-*/

    //stat_create_session_req_err_table_sgw,

    stat_business_gtp_pkt,
    stat_business_unknown_gtp_pkt,
    stat_business_gtp_permit_pkt,
    stat_business_gtp_drop_pkt,
    stat_business_gtp_fwd_pkt,
    stat_business_outerl4_udp,
    stat_business_innerl4_udp,
    stat_business_outerl4_tcp,
    stat_business_innerl4_tcp,
    //sctp
    stat_business_outerl4_sctp,
    stat_business_innerl4_sctp,
    stat_business_multi_data_chunk_sctp,

    stat_business_s1ap_pkt,
    stat_business_not_s1ap_pkt,
    stat_business_s1ap_match_port_pkt,
    stat_business_s1ap_not_match_port_pkt,
    stat_business_s1ap_custom_port_pkt,
    stat_business_s1ap_not_custom_port_pkt,
    stat_business_s1ap_permit_pkt,
    stat_business_s1ap_drop_pkt,
    stat_business_s1ap_fwd_pkt,

    //diameter
    stat_business_dmt_pkts,
    stat_business_dmt_standard_port_pkts,
    stat_business_dmt_custom_port_pkts,
    stat_business_dmt_error_ppid_pkts,
    stat_business_dmt_version_err_pkts,
    stat_business_dmt_cmd_not_318_pkts,
    stat_business_dmt_not_3gpp_app_pkts,
    stat_business_dmt_auth_request_pkts,
    stat_business_dmt_auth_response_pkts,
    stat_dmt_auth_request_pkts,
    stat_dmt_auth_response_pkts,
    stat_dmt_auth_request_related_pkts,
    stat_dmt_auth_response_related_pkts,
    stat_business_dmt_usr_too_long,
    stat_dmt_usrName_bcd_code_too_long,
    stat_business_dmt_too_many_kasme_rand_pair,
    stat_business_dmt_auth_msg_incompelte,
    stat_business_dmt_auth_req_search_s6a_fail,
    stat_diameter_pkt_permit,
    stat_diameter_pkt_forward,
    stat_diameter_pkt_drop,
    stat_diameter_pkt_rand_too_long,
    stat_diameter_pkt_rand_too_short,
    stat_diameter_pkt_kasme_too_long,
    stat_diameter_pkt_kasme_too_short,
    stat_diameter_auth_ans_pkt_without_key,

    stat_s1ap_tai_too_long,
    stat_s1ap_ecgi_too_long,


    /* m3ua packet statistics define */
    stat_business_iups_msg_num,
    stat_business_over_iups_pkts,
    stat_business_m3ua_pkts,
    stat_business_m3ua_pkts_class_trans,
    stat_business_m3ua_pkts_class_others,
    stat_business_m3ua_pkts_proto_sccp,
    stat_business_m3ua_pkts_proto_others,
    stat_business_m3ua_pkts_bad,
    /* m3ua packet statistics end*/

    /* sccp packet statistics define */
    stat_business_sccp_pkts_CR,
    stat_business_sccp_pkts_CC,
    stat_business_sccp_pkts_CREF,
    stat_business_sccp_pkts_RLSD,
    stat_business_sccp_pkts_RLC,
    stat_business_sccp_pkts_DT1,
    stat_business_sccp_pkts_DT2,
    stat_business_sccp_pkts_AK,
    stat_business_sccp_pkts_UDT,
    stat_business_sccp_pkts_UDTS,
    stat_business_sccp_pkts_ED,
    stat_business_sccp_pkts_EA,
    stat_business_sccp_pkts_RSR,
    stat_business_sccp_pkts_RSC,
    stat_business_sccp_pkts_ERR,
    stat_business_sccp_pkts_IT,
    stat_business_sccp_pkts_XUDT,
    stat_business_sccp_pkts_XUDTS,
    stat_business_sccp_pkts_LUDT,
    stat_business_sccp_pkts_LUDTS,
    stat_business_sccp_pkts_unkown_type,
    stat_business_sccp_pkts_reassembling,
    stat_business_sccp_pkts_bad,
    stat_business_sccp_pkts_NULL_CR,
    stat_business_sccp_pkts_NULL_CC,
    /* sccp packet statistics end*/

    /*ranap packet statistics*/
    stat_business_ranap_pkts_InitialUEMsg,
    stat_business_ranap_pkts_DirectTransfer,
    stat_business_ranap_pkts_CommonID,
    stat_business_ranap_pkts_IuReleaseCommand,
    stat_business_ranap_pkts_RabAssigmentReq,
    stat_business_ranap_pkts_SetOrModifyList_more,  //一个RabAssigmentReq报文包含多于1个SetOrModifyList
    stat_business_ranap_pkts_SetOrModifyItem_more,  //一个SetOrModifyList报文包含多于1个SetOrModifyItem
    stat_business_ranap_pkts_RabAssigmentRes,
    stat_business_ranap_pkts_SetOrModifiedList_more,  //一个RabAssigmentRes报文包含多于1个SetOrModifiedList
    stat_business_ranap_pkts_SetOrModifiedItem_more,  //一个SetOrModifyList报文包含多于1个SetOrModifiedItem
    stat_business_ranap_pkts_Invalid_Packet,
    stat_business_ranap_pkts_not_PSdomain,
    stat_business_ranap_pkts_LAI_IEextbit,
    stat_business_ranap_pkts_LAI_pkt_len_error,
    stat_business_ranap_pkts_RAC_pkt_len_error,
    stat_business_ranap_pkts_PerNASUEID_extbit,
    stat_business_ranap_pkts_PerNASUEID_pktLenError,
    stat_business_ranap_pkts_transAddr_extbit,
    stat_business_ranap_pkts_transAddr_pktLenError,
    stat_business_ranap_pkts_transAddr_notIPv4orIPv6,
    stat_business_ranap_pkts_transAss_extbit,
    stat_business_ranap_pkts_transAss_not_teid,
    stat_business_ranap_pkts_rabPara_extbit,
    stat_business_ranap_pkts_rabPara_IEextbit,
    stat_business_ranap_pkts_trafficClass_extbit,
    stat_business_ranap_pkts_rABAsymmetry_extbit,
    stat_business_ranap_pkts_sDU_Para_extbit,
    stat_business_ranap_pkts_sDU_Para_IEextbit,
    stat_business_ranap_pkts_sDU_ErrRatio_IEextbit,
    stat_business_ranap_pkts_residualBit_IEextbit,
    stat_business_ranap_pkts_sDUFormatInfo_extbit,
    stat_business_ranap_pkts_sDUFormatInfo_IEextbit,
    stat_business_ranap_pkts_allocation_extbit,
    stat_business_ranap_pkts_allocation_IEextbit,
    stat_business_ranap_pkts_sourceStatDesc_extbit,
    stat_business_ranap_pkts_relocationReq_extbit,
    stat_business_ranap_pkts_RABModifyItF_extbit,
    stat_business_ranap_pkts_RABModifyItF_IEextbit,
    stat_business_ranap_pkts_RABModifyItFNOTransinfo,
    stat_business_ranap_pkts_RABuserPlaneInfo_extbit,
    stat_business_ranap_pkts_RABuserPlaneInfo_IEextbit,
    stat_business_ranap_pkts_RABuserPlaneMode_extbit,
    stat_business_ranap_pkts_RABtransInfo_extbit,
    stat_business_ranap_pkts_RABtransInfo_IEextbit,
    stat_business_ranap_pkts_RABModifiedIt_extbit,
    stat_business_ranap_pkts_RABModifiedIt_IEextbit,
    stat_business_ranap_pkts_RABModifiedItno_ip_teid,
    stat_business_ranap_pkts_initialUEMsg_extbit,
    stat_business_ranap_pkts_initialUEMsg_IEextbit,
    stat_business_ranap_pkts_invalid_initialUEMsg,
    stat_business_ranap_pkts_commonID_extbit,
    stat_business_ranap_pkts_commonID_IEextbit,
    stat_business_ranap_pkts_invalid_commonID,
    stat_business_ranap_pkts_DirectTransfer_extbit,
    stat_business_ranap_pkts_DirectTransfer_IEextbit,
    stat_business_ranap_pkts_invalid_DirectTransfer,
    stat_business_ranap_pkts_RABAssigReq_extbit,
    stat_business_ranap_pkts_RABAssigReq_IEextbit,
    stat_business_ranap_pkts_invalid_RABAssigReq,
    stat_business_ranap_pkts_RABAssigRes_extbit,
    stat_business_ranap_pkts_RABAssigRes_IEextbit,
    stat_business_ranap_pkts_invalid_RABAssigRes,
    stat_business_ranap_pkts_initiMsg_not_care,
    stat_business_ranap_pkts_outcome_not_care,
    stat_business_ranap_pkts_succoutcome_packet,
    stat_business_ranap_pkts_unsuccoutcome_packet,
    stat_business_ranap_pkts_RANAPpdu_extbit,
    stat_business_ranap_pkts_Unknown_Packet,
    stat_business_ranap_pkts_all_packet,
    stat_business_ranap_pkts_initiating_packet,
    stat_business_ranap_pkts_outcome_packet,
    stat_business_ranap_pkts_num,   //不管sctp有几个data chunk，只要包含有有效ranap，则数量加1
    stat_business_ranap_pkts_size,  //包含ranap的报文的总长度
    stat_business_ranap_permit_pkt,
    stat_business_ranap_drop_pkt,
    stat_business_ranap_fwd_pkt,


    /*************GMM nas stattictics*************/

    stat_ms_identity_imeisv,
    stat_attach_request_packet,
    stat_attach_request_bad_packet,
    stat_attach_request_ms_identity_parse_err,
    stat_attach_accept_packet,
    stat_attach_accept_bad_packet,
    stat_attach_accept_ms_identity_parse_err,
    stat_identity_response_packet,
    stat_identity_response_ms_identity_parse_err,
    stat_rau_request_packet,
    stat_rau_request_bad_packet,
    stat_rau_request_ptmsi_err,
    stat_rau_accept_packet,
    stat_rau_accept_bad_packet,
    stat_rau_accept_ms_identity_parse_err,
    stat_ptmsi_reloc_cmd_packet,
    stat_ptmsi_reloc_cmd_ptmsi_parse_err,
    stat_gmm_deteach_packet,
    stat_gmm_other_message_packet,
    stat_not_gmm_nas_packet,
    /*******************end********************/


    stat_business_v4mask_pkt,
    stat_business_v4mask_permit_pkt,
    stat_business_v4mask_drop_pkt,
    stat_business_v4mask_fwd_pkt,
    stat_business_str_pkt,
    stat_business_str_permit_pkt,
    stat_business_str_drop_pkt,
    stat_business_str_fwd_pkt,
    stat_business_process_fail,
    stat_business_action_drop,
    stat_business_action_fwd,

    //出口组添加lte信息相关的统计信息
    stat_oifgrp_xmit_pkts,
    stat_oifgrp_add_timestamp_pkts,
    stat_oifgrp_add_timestamp_fail,
    stat_add_lte_info_success,
    stat_oifgrp_add_imsi_pkts,
    stat_oifgrp_add_imei_pkts,
    stat_oifgrp_add_msisdn_pkts,
    stat_oifgrp_add_tai_pkts,
    stat_oifgrp_add_guti_pkts,
    stat_oifgrp_add_imsi_fail,
    stat_oifgrp_add_imei_fail,
    stat_oifgrp_add_msisdn_fail,
    stat_oifgrp_add_tai_fail,
    stat_oifgrp_add_guti_fail,
    stat_oifgrp_pkt_too_log,
    stat_unknow_cell_net,

    //出口组添加3g信息的统计
    stat_oifgrp_add_rai_pkts,
    stat_oifgrp_add_rai_fail,

    stat_business_xmit_fwd,
    stat_business_xmit_fwd_fail,
    stat_build_send_pkt_fail,
    stat_soft_work_null,

    stat_business_fwd_zero_oifgrp,
    stat_business_action_unknown,
    stat_timer_pkt,
    stat_unknown_pkt,
    stat_pkts_below_64,
    stat_pkts_between_64_128,
    stat_pkts_between_128_256,
    stat_pkts_between_256_512,
    stat_pkts_between_512_1024,
    stat_pkts_between_1024_1500,
    stat_pkts_between_1500_1600,
    stat_pkts_above_1600,
    stat_very_short_pkts,
    stat_very_long_pkts,
    stat_normal_pkts,
    stat_business_pkt_free,
    stat_business_pkt_unfree,
    stat_business_wqe_free,
    stat_unknown_ether_pkt,
    stat_business_vlan_pkt,
    stat_business_not_vlan_pkt,
    stat_max
} hydra_stat_e;

struct stat_compare_s
{
    hydra_stat_e  stat;
    char  *stat_name;
};


#define hydra_stat_inc(t) do{}while(0)
#define HYDRA_STAT_INC(t) do{}while(0)
#define INC_STATS_PKTS(t,t1) do{}while(0)

#endif /* HYDRA_STAT_H_ */
